spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springsessiontest
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

##redis
  redis:
    database: 7
    host:
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0